name:                malfunction
version:             0.1.0.0
github:              "susisu/malfunction"
license:             BSD3
author:              "Susisu"
maintainer:          "susisu2413@yahoo.co.jp"
copyright:           "copyright (c) 2018 Susisu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/susisu/malfunction#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  malfunction-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - malfunction

tests:
  malfunction-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - malfunction
